AP_COMPONENT := yes
AP_TYPE := adapter

NAME := socketcan

API := can
PLATFORM := linux

SRCS := \
	socketcan.c

INC_DIRS := \
	$(PROJECT_ROOT)/plugins/can/include \
	$(PROJECT_ROOT)/core/include

include $(PROJECT_ROOT)/mk/adapter.mk