#include <stdio.h>
#include <time.h>

#include "ap_core.h"
#include "ap_config_reader.h"
#include "ap_plugin_manager.h"
#include "result_string.h"


int main(int argc, char **argv)
{
    ap_result_t result;

    printf("=========================================\n");
    printf(" Automation Platform - Core Test\n");
    printf("=========================================\n\n");

    result = ap_core_init();

    if (result != AP_OK)
    {
        printf("Core initialization failed: %s\n",ap_result_string(result));
        return 1;
    }

    const char *config_path = "build/config.bin";

    if (argc > 1)
    {
        config_path = argv[1];
    }

    result = ap_config_reader_open(config_path);
    if (result != AP_OK)
    {
        printf("Config open failed: %s\n",ap_result_string(result));
        ap_core_shutdown();
        return 1;
    }

    /*
     * Load and initialize configured plugins.
     */
    result = ap_plugin_manager_init();

    printf("AP: Plugin types registered: %u\n",ap_plugin_manager_get_plugin_types_registered());
    printf("AP: Plugin instances loaded: %u\n",ap_plugin_manager_get_plugin_instances_loaded());

    ap_config_reader_close();

    if (result != AP_OK)
    {
        printf("Plugin manager initialization failed: %s\n",ap_result_string(result));
        ap_plugin_manager_shutdown();
        ap_core_shutdown();
        return 1;
    }

    printf("Plugins initialized successfully.\n");

    while (1)
    {
        /*
         * Process plugin backends first.
         *
         * Backend RX data can generate Core events.
         */
        result = ap_plugin_manager_process();
        if (result != AP_OK)
        {
            printf("Plugin manager process failed: %s\n",ap_result_string(result));
            break;
        }

        /*
         * Process events generated by plugins.
         */
        result = ap_core_process();
        if (result != AP_OK)
        {
            printf("Core process failed: %s\n",ap_result_string(result));
            break;
        }

        struct timespec delay =
        {
            .tv_sec = 0,
            .tv_nsec = 100000000
        };
        nanosleep(&delay,NULL);
    }

    ap_plugin_manager_shutdown();
    ap_core_shutdown();
    printf("\nShutdown Done.\n");
    return 0;
}
