AP_COMPONENT := yes
AP_TYPE := adapter

NAME := tcp
API := tcp

PLATFORM := linux

SRCS := \
	$(wildcard *.c)

INC_DIRS := \
	$(PROJECT_ROOT)/core/include \
	$(PROJECT_ROOT)/adapters/api \

include $(PROJECT_ROOT)/mk/adapter.mk